INSERT INTO [db_archive].[0121].[input_form_fields_list] VALUES
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'template', 'string', dbo.get_field_name('template')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'organization_code', 'string', dbo.get_field_name('organization_code')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'organization', 'string', dbo.get_field_name('organization')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'timestamp', 'datetime', dbo.get_field_name('timestamp')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'last_update', 'datetime', dbo.get_field_name('last_update')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'Найменування виду економічної діяльності', 'string', dbo.get_field_name('Найменування виду економічної діяльності')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'Одиниця виміру', 'string', dbo.get_field_name('Одиниця виміру')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'Код рядка', 'string', dbo.get_field_name('Код рядка')),
( '[db_archive].[0121].[vvedennya_v_diyu_potuzhnostey]', 'Всього', 'number', dbo.get_field_name('Всього')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'template', 'string', dbo.get_field_name('template')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'organization_code', 'string', dbo.get_field_name('organization_code')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'organization', 'string', dbo.get_field_name('organization')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'timestamp', 'datetime', dbo.get_field_name('timestamp')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'last_update', 'datetime', dbo.get_field_name('last_update')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'Заборгованість', 'string', dbo.get_field_name('Заборгованість')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'Код рядка', 'string', dbo.get_field_name('Код рядка')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'Всього', 'number', dbo.get_field_name('Всього')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'у тому числі постачальним організаціям', 'number', dbo.get_field_name('у тому числі постачальним організаціям')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'у тому числі проєктним організаціям', 'number', dbo.get_field_name('у тому числі проєктним організаціям')),
( '[db_archive].[0121].[dovidka_pro_zaborhovanist]', 'у тому числі підрядним організаціям', 'number', dbo.get_field_name('у тому числі підрядним організаціям'))