// Єдиний запит
let
    Функція = let
        Джерело = (Параметр1) => let
            Джерело = Excel.Workbook(Параметр1, null, true)
        in
            Джерело
    in
        Джерело,
    #"Енергопідприємства" =
        let
        Джерело = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lVfbThpRFP0VwlOb1GQu3OZbtB/QD+i7tS2+NKmlFBssKBjpi0mpqCUU8Bf2/FHXvhydOTMINYqjnLXOvqx9YX+/GlZfVYMgCIMAD9Sl88pBlQb0jfr8cEmL9JDuaEV3+D2j9UG1gq/q61f71UiRsSLP6YTGDOnSWNB4WKU9egBuXWTwvoQwVsJagXAN9G+apu/KeARaM2gs0DENqZOzZZR+hC23ebwg64qsb/LiFPduwjYU2/CwEz6aHpUFTq1tKq4ZKg4HDKnhnvF15WETeEvhrQJ8QHO6x9WfAL3l6KfvxIw13eDpEy1oWqGv8GvEbMKVgCJJksBL/4kTwLcnCxCII7wuCwkUIjEGaoiDMBeMK8AO4VYvawPHdrJX38CkkozwnbFplHbpRkxh39ZiVjvHJ2zKoNKMfFuGnEXPCs8GxasSo8jD/0B8F7j7L3w6LfizwRuVZlxTbzJxgS9QNDzZxuOYVKph6FmVrbOiTQptOChrh/o4O0c017CgR3+eEBO7SQUa1fUmy0AfF55BoiO65meXRagF1UYn7ipVZxxFLa8UOxUcnaYfREUzmtIfNhiGcDp/p+/xvGIzOMJLesABVvBnx5uoC42WxLHvbJpLJo5QKg/Iy7qkSiNVZmjZRBIlVKsSSep5019Nz/eljpdS08fpe090ilC9oRPmM/NTLFlw5xLQXUVayZJDL8YuYCxX9ovCUcf/Ui8QQaIi6mEuqB8Q+Asa7uEF9Yr/DpCdMf66xF8TatMvIe9KDa7geLuM3Jpn4rWxDkxdGeozpwgmP9PHlcs0Gvhc4vDcetMWJqN61OzG+TKAh+ccAPCrKtsVvHcmwRjLGz/wzMHpUfvpGuVvOlls5B/KIJz8B7NRaw2E/mi0ntpDSKWTmhKfCYfSmfT9wYjRJIo55GJBoz/amiYds1YPNvI6WboH6wn3dL8958oWuroMvWn0GMg+fafjHVOknFpPYdNz2Kr9GbsUru07bPlwtBNpktx/8DTVzuNTKUfNhlCU3yjO0Kdm0ppcScPyoQOp+iNfsmc4esPtpnidWdxwAycP9AbO1tJRsqabfqXqsyEIH3ZKb8s1wzzZOVsFFU9h1UYmZUjcMPEYZAjtoF9d8FS0kb9rXUhYcXoz0tq5r4YRMokK3LGx1WylSLyiGQsKXRwDuIeIbG1vyha7ZUnYTjQzmVVphyZpTI/rRWmyM1vGLq2hpgKO/Vxdyfxj756GyC50DTcX83SZYbd7AlTVsV9b5qhS6kxv47WUVIncglJqFDPMns2AkiQ2kMPs3nyB4zO5HIuMhivtVThy+FnIKj5Pj/WfS6G9Q5/tuU8igXHqklYcSB300RHqty8Db4gmeo23BtxRiz1UNgVs9pHMOZBImH5J8bNg0bh4xfqri6ADRQaSDdi59YV1efAW6m+mXTzZ2djOBvXsmg7HZNS7UzU9ZWnD57A3dMsfQk5hkMXz9T8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"№" = _t, #"Код підприємства" = _t, #"Назва підприємства" = _t])
    in
        Джерело,
    #"Джерело_даних" = Folder.Files("C:\Users\Asus\Documents\Work\0120\Історичні дані"),
    #"Відфільтровані приховані файли1" = Table.SelectRows(#"Джерело_даних", each [Attributes]?[Hidden]? <> true),
    #"Викликати спеціальну функцію1" = Table.AddColumn(#"Відфільтровані приховані файли1", "Функція", each #"Функція"([Content])),
    #"Відфільтровані рядки" = Table.SelectRows(#"Викликати спеціальну функцію1", each ([Extension] <> ".pdf")),
    #"Доданий індекс" = Table.AddIndexColumn(#"Відфільтровані рядки", "Індекс", 1, 1, Int64.Type),
    #"Відсортовані рядки" = Table.Sort(#"Доданий індекс",{{"Індекс", Order.Ascending}}),
    #"Розгорнуто: Перетворити файл" = Table.ExpandTableColumn(#"Відсортовані рядки", "Функція", {"Name", "Data"}, {"Name.1", "Data"}),
    #"Розгорнуто: Data" = Table.ExpandTableColumn(#"Розгорнуто: Перетворити файл", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16"}),
    #"Поділ стовпця за роздільником" = Table.SplitColumn(#"Розгорнуто: Data", "Name", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"Name.1.1", "Name.2", "Name.3", "Name.4"}),
    #"Поділ стовпця за роздільником1" = Table.SplitColumn(#"Поділ стовпця за роздільником", "Name.4", Splitter.SplitTextByEachDelimiter({"."}, QuoteStyle.Csv, false), {"Name.4.1", "Name.4.2"}),
    #"Змінений тип1" = Table.TransformColumnTypes(#"Поділ стовпця за роздільником1",{{"Name.4.1", Int64.Type}, {"Name.4.2", type text}}),
    #"Об’єднані стовпці1" = Table.CombineColumns(Table.TransformColumnTypes(#"Змінений тип1", {{"Name.4.1", type text}}, "uk-UA"),{"Name.3", "Name.4.1"},Combiner.CombineTextByDelimiter(".", QuoteStyle.None),"Об’єднано"),
    Спеціальне1 = Table.TransformColumns( #"Об’єднані стовпці1",{{"Об’єднано", each "01." & _}} ),
    #"Видалені інші стовпці" = Table.SelectColumns(Спеціальне1,{"Name.1.1", "Name.2", "Об’єднано", "Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Індекс"}),
    #"Транспонована таблиця2" = Table.Transpose(#"Видалені інші стовпці"),
    #"Транспонована таблиця3" = Table.Transpose(#"Транспонована таблиця2"),
    #"Перейменовані стовпці" = Table.RenameColumns(#"Транспонована таблиця3",{{"Column1", "template"}, {"Column2", "organization"}, {"Column3", "datetime"}, {"Column4", "Види активів"}, {"Column5", "Код рядка"}, {"Column18", "Будівельні та монтажні роботи"}, {"Column19", "Введення в дію основних фондів"}, {"Column20", "Індекс"}, {"Column6", "Профінансовано всього"}, {"Column7", "Профінансовано у тому числі  за джерелами фінансування кошти державного бюджету"}, {"Column8", "Профінансовано у тому числі  за джерелами фінансування власні кошти підприємств"}, {"Column17", "Капітальні вкладення у тому числі  за джерелами фінансування інші джерела"}, {"Column9", "Профінансовано у тому числі  за джерелами фінансування кредити комерційних банків"}, {"Column10", "Профінансовано у тому числі  за джерелами фінансування кредити МФО"}, {"Column11", "Профінансовано у тому числі  за джерелами фінансування інші джерела"}, {"Column12", "Капітальні вкладення Всього"}, {"Column13", "Капітальні вкладення у тому числі  за джерелами фінансування кошти державного бюджету"}, {"Column14", "Капітальні вкладення у тому числі  за джерелами фінансування власні кошти підприємств"}, {"Column15", "Капітальні вкладення у тому числі  за джерелами фінансування кредити комерційних банків"}, {"Column16", "Капітальні вкладення у тому числі  за джерелами фінансування кредити МФО"}}),
    #"Відфільтровані рядки1" = Table.SelectRows(#"Перейменовані стовпці", each ([Код рядка] <> null and [Код рядка] <> "                  МІНЕНЕРГО  УКРАЇНИ" and [Код рядка] <> "    ВП ""Укренергосервіс"" ДП ""НЕК ""Укренерго""" and [Код рядка] <> "Б" and [Код рядка] <> "Код рядка")),
    #"Замінене значення" = Table.ReplaceValue(#"Відфільтровані рядки1","((","",Replacer.ReplaceText,{"Види активів"}),
    #"Змінений тип2" = Table.TransformColumnTypes(#"Замінене значення",{{"Будівельні та монтажні роботи", type text}}),
    #"Обітнутий текст1" = Table.TransformColumns(#"Змінений тип2",{{"Будівельні та монтажні роботи", Text.Trim, type text}, {"Види активів", Text.Trim, type text}}),
    #"Замінене значення1" = Table.ReplaceValue(#"Обітнутий текст1","Х","",Replacer.ReplaceText,{"Будівельні та монтажні роботи"}),
    #"Додане настроюване значення" = Table.AddColumn(#"Замінене значення1", "status", each "archived"),
    #"Додане настроюване значення1" = Table.AddColumn(#"Додане настроюване значення", "last_update", each DateTime.FixedLocalNow()),
    #"Об’єднані запити" = Table.NestedJoin(#"Додане настроюване значення1", {"organization"}, #"Енергопідприємства", {"Код підприємства"}, "Підприємства", JoinKind.LeftOuter),
    #"Розгорнуто: Підприємства" = Table.ExpandTableColumn(#"Об’єднані запити", "Підприємства", {"Назва підприємства"}, {"Назва підприємства"}),
    #"Змінений тип" = Table.TransformColumnTypes(#"Розгорнуто: Підприємства",{{"datetime", type datetime}, {"template", type text}, {"organization", type text}, {"Код рядка", type text}, {"Профінансовано всього", type number}, {"Профінансовано у тому числі  за джерелами фінансування кошти державного бюджету", type number}, {"Профінансовано у тому числі  за джерелами фінансування власні кошти підприємств", type number}, {"Профінансовано у тому числі  за джерелами фінансування кредити комерційних банків", type number}, {"Профінансовано у тому числі  за джерелами фінансування кредити МФО", type number}, {"Профінансовано у тому числі  за джерелами фінансування інші джерела", type number}, {"Капітальні вкладення Всього", type number}, {"Капітальні вкладення у тому числі  за джерелами фінансування кошти державного бюджету", type number}, {"Капітальні вкладення у тому числі  за джерелами фінансування власні кошти підприємств", type number}, {"Капітальні вкладення у тому числі  за джерелами фінансування кредити комерційних банків", type number}, {"Капітальні вкладення у тому числі  за джерелами фінансування кредити МФО", type number}, {"Капітальні вкладення у тому числі  за джерелами фінансування інші джерела", type number}, {"Будівельні та монтажні роботи", type number}, {"Введення в дію основних фондів", type number}, {"Індекс", Int64.Type}, {"status", type text}, {"last_update", type datetime}}),
    #"Видалені інші стовпці1" = Table.SelectColumns(#"Змінений тип",{"template", "organization", "Назва підприємства", "status", "datetime", "last_update", "Види активів", "Код рядка", "Профінансовано всього", "Профінансовано у тому числі  за джерелами фінансування кошти державного бюджету", "Профінансовано у тому числі  за джерелами фінансування власні кошти підприємств", "Профінансовано у тому числі  за джерелами фінансування кредити комерційних банків", "Профінансовано у тому числі  за джерелами фінансування кредити МФО", "Профінансовано у тому числі  за джерелами фінансування інші джерела", "Капітальні вкладення Всього", "Капітальні вкладення у тому числі  за джерелами фінансування кошти державного бюджету", "Капітальні вкладення у тому числі  за джерелами фінансування власні кошти підприємств", "Капітальні вкладення у тому числі  за джерелами фінансування кредити комерційних банків", "Капітальні вкладення у тому числі  за джерелами фінансування кредити МФО", "Капітальні вкладення у тому числі  за джерелами фінансування інші джерела", "Будівельні та монтажні роботи", "Введення в дію основних фондів"})
in
    #"Видалені інші стовпці1"