//w0
let
    Джерело = Access.Database(File.Contents("C:\Users\Asus\OneDrive - ТОВ УКРЕНЕРГО ЦИФРОВІ РІШЕННЯ\Документи\Work\15506\access\RAB_W01.accdb"), [CreateNavigationProperties=true]),
    _RAB_W0 = Джерело{[Schema="",Item="RAB_W0"]}[Data],
    #"Відфільтровані рядки" = Table.SelectRows(_RAB_W0, each ([DATA] <> "712" and [DATA] <> "903" and [DATA] <> "910" and [DATA] <> "9911") and ([KPO] <> "0003" and [KPO] <> "0004" and [KPO] <> "0005" and [KPO] <> "0006" and [KPO] <> "0012" and [KPO] <> "0016" and [KPO] <> "0024")),
    #"Інші стовпці, зведення яких скасовано" = Table.UnpivotOtherColumns(#"Відфільтровані рядки", {"REL", "VID_INF", "DATA", "KPO", "PRIS_INF", "KOD_GR_O", "PR_TOP_O"}, "Атрибут", "Значення"),
    #"Змінений тип" = Table.TransformColumnTypes(#"Інші стовпці, зведення яких скасовано",{{"KOD_GR_O", Int64.Type}, {"PR_TOP_O", Int64.Type}}),
    #"Розділити стовпець за положенням" = Table.SplitColumn(#"Змінений тип", "DATA", Splitter.SplitTextByPositions({0, 2}, false), {"DATA.1", "DATA.2"}),
    #"Додане настроюване значення" = Table.AddColumn(#"Розділити стовпець за положенням", "Date", each "01" & "." & [DATA.2] & "." &  [DATA.1]),
    #"Змінений тип1" = Table.TransformColumnTypes(#"Додане настроюване значення",{{"Date", type date}}),
    #"Обітнутий текст" = Table.TransformColumns(#"Змінений тип1",{{"Значення", Text.Trim, type text}}),
    #"Відфільтровані рядки1" = Table.SelectRows(#"Обітнутий текст", each ([Атрибут] <> "N_GR1" and [Атрибут] <> "N_GR2" and [Атрибут] <> "N_GR3")),
    #"Замінене значення1" = Table.ReplaceValue(#"Відфільтровані рядки1",".",",",Replacer.ReplaceText,{"Значення"}),
    #"Замінене значення" = Table.ReplaceValue(#"Замінене значення1","-","",Replacer.ReplaceText,{"Значення"}),
    #"Видалені стовпці" = Table.RemoveColumns(#"Замінене значення",{"DATA.1", "DATA.2"}),
    #"Змінений тип2" = Table.TransformColumnTypes(#"Видалені стовпці",{{"Значення", type number}}),
    #"Об’єднані запити" = Table.NestedJoin(#"Змінений тип2", {"KPO", "KOD_GR_O", "PR_TOP_O"}, Групи, {"Station", "KOD_GR", "PR_TOP"}, "Групи", JoinKind.LeftOuter),
    #"Розгорнуто: Групи" = Table.ExpandTableColumn(#"Об’єднані запити", "Групи", {"Атрибут"}, {"Атрибут.1"}),
    #"Відфільтровані рядки2" = Table.SelectRows(#"Розгорнуто: Групи", each ([Атрибут.1] <> null)),
    #"Зведений стовпець" = Table.Pivot(#"Відфільтровані рядки2", List.Distinct(#"Відфільтровані рядки2"[Атрибут.1]), "Атрибут.1", "Значення", List.Sum),
    #"Згруповані рядки" = Table.Group(#"Зведений стовпець", {"VID_INF", "KPO", "Атрибут", "Date"}, {{"Група N1", each List.Sum([Група N1]), type nullable number}, {"Група N2", each List.Sum([Група N2]), type nullable number}, {"Група N3", each List.Sum([Група N3]), type nullable number}, {"Всього", each List.Sum([Всього]), type nullable number}}),
    #"Об’єднані запити1" = Table.NestedJoin(#"Згруповані рядки", {"Атрибут"}, Headers, {"Заголовки"}, "Headers", JoinKind.LeftOuter),
    #"Розгорнуто: Headers" = Table.ExpandTableColumn(#"Об’єднані запити1", "Headers", {"№ п/п", "Показник", "Позначення"}, {"N", "Показник", "Позначення"}),
    #"Поділ стовпця за роздільником" = Table.SplitColumn(#"Розгорнуто: Headers", "Показник", Splitter.SplitTextByEachDelimiter({","}, QuoteStyle.Csv, true), {"Показник", "Розмірність"}),
    #"Об’єднані запити2" = Table.NestedJoin(#"Поділ стовпця за роздільником", {"KPO"}, #"Список станцій", {"organization code"}, "Список станцій", JoinKind.LeftOuter),
    #"Розгорнуто: Список станцій" = Table.ExpandTableColumn(#"Об’єднані запити2", "Список станцій", {"organization"}, {"organization"}),
    #"Додане настроюване значення1" = Table.AddColumn(#"Розгорнуто: Список станцій", "last update", each DateTime.LocalNow(), type datetime),
    #"Додане настроюване значення2" = Table.AddColumn(#"Додане настроюване значення1", "Name", each "RAB_W0", type text),
    #"Додане настроюване значення3" = Table.AddColumn(#"Додане настроюване значення2", "Status", each "archived", type text),
    #"Додане настроюване значення5" = Table.AddColumn(#"Додане настроюване значення3", "TableType", each "Загальностанційні показники", type text),
    #"Додане настроюване значення4" = Table.AddColumn(#"Додане настроюване значення5", "Група N4", each null, type number),
    #"Перейменовані стовпці" = Table.RenameColumns(#"Додане настроюване значення4",{{"VID_INF", "template"}, {"KPO", "organization code"}, {"Date", "timestamp"}}),
    #"Змінений тип3" = Table.TransformColumnTypes(#"Перейменовані стовпці",{{"timestamp", type datetime}, {"N", type text}}),
    #"Видалені інші стовпці" = Table.SelectColumns(#"Змінений тип3",{"Name", "template", "organization code", "organization", "timestamp", "last update", "Status", "N", "Показник", "Розмірність", "Позначення", "Група N1", "Група N2", "Група N3", "Група N4", "Всього", "TableType"})
in
    #"Видалені інші стовпці"



//w1
let
    Джерело = Access.Database(File.Contents("C:\Users\Asus\OneDrive - ТОВ УКРЕНЕРГО ЦИФРОВІ РІШЕННЯ\Документи\Work\15506\access\RAB_W11.accdb"), [CreateNavigationProperties=true]),
    _RAB_W1 = Джерело{[Schema="",Item="RAB_W1"]}[Data],
    #"Відфільтровані рядки" = Table.SelectRows(_RAB_W1, each ([DATA] <> "712" and [DATA] <> "903" and [DATA] <> "910" and [DATA] <> "9911") and ([KPO] <> "0003" and [KPO] <> "0004" and [KPO] <> "0005" and [KPO] <> "0006" and [KPO] <> "0012" and [KPO] <> "0016" and [KPO] <> "0024")),
    #"Інші стовпці, зведення яких скасовано" = Table.UnpivotOtherColumns(#"Відфільтровані рядки", {"REL", "template", "DATA", "organization code", "PRIS_INF", "KOD_GR_T", "PR_TOP_T"}, "Атрибут", "Значення"),
    #"Змінений тип" = Table.TransformColumnTypes(#"Інші стовпці, зведення яких скасовано",{{"KOD_GR_T", Int64.Type}, {"PR_TOP_T", Int64.Type}}),
    #"Розділити стовпець за положенням" = Table.SplitColumn(#"Змінений тип", "DATA", Splitter.SplitTextByPositions({0, 2}, false), {"DATA.1", "DATA.2"}),
    #"Додане настроюване значення" = Table.AddColumn(#"Розділити стовпець за положенням", "timestamp", each "01" & "." & [DATA.2] & "." &  [DATA.1]),
    #"Змінений тип1" = Table.TransformColumnTypes(#"Додане настроюване значення",{{"timestamp", type date}}),
    #"Обітнутий текст" = Table.TransformColumns(#"Змінений тип1",{{"Значення", Text.Trim, type text}}),
    #"Відфільтровані рядки1" = Table.SelectRows(#"Обітнутий текст", each ([Атрибут] <> "N_GR1" and [Атрибут] <> "N_GR2" and [Атрибут] <> "N_GR3")),
    #"Замінене значення1" = Table.ReplaceValue(#"Відфільтровані рядки1",".",",",Replacer.ReplaceText,{"Значення"}),
    #"Замінене значення" = Table.ReplaceValue(#"Замінене значення1","-","",Replacer.ReplaceText,{"Значення"}),
    #"Видалені стовпці" = Table.RemoveColumns(#"Замінене значення",{"DATA.1", "DATA.2"}),
    #"Змінений тип2" = Table.TransformColumnTypes(#"Видалені стовпці",{{"Значення", type number}}),
    #"Об’єднані запити" = Table.NestedJoin(#"Змінений тип2", {"organization code", "KOD_GR_O", "PR_TOP_O"}, Групи, {"Station", "KOD_GR", "PR_TOP"}, "Групи", JoinKind.LeftOuter),
    #"Розгорнуто: Групи" = Table.ExpandTableColumn(#"Об’єднані запити", "Групи", {"Атрибут"}, {"Атрибут.1"}),
    #"Відфільтровані рядки2" = Table.SelectRows(#"Розгорнуто: Групи", each ([Атрибут.1] <> null)),
    #"Зведений стовпець" = Table.Pivot(#"Відфільтровані рядки2", List.Distinct(#"Відфільтровані рядки2"[Атрибут.1]), "Атрибут.1", "Значення", List.Sum),
    #"Згруповані рядки" = Table.Group(#"Зведений стовпець", {"template", "organization code", "Атрибут", "timestamp"}, {{"Група N1", each List.Sum([Група N1]), type nullable number}, {"Група N2", each List.Sum([Група N2]), type nullable number}, {"Група N3", each List.Sum([Група N3]), type nullable number}, {"Всього", each List.Sum([Всього]), type nullable number}}),
    #"Об’єднані запити1" = Table.NestedJoin(#"Згруповані рядки", {"Атрибут"}, Headers, {"Заголовки"}, "Headers", JoinKind.LeftOuter),
    #"Розгорнуто: Headers" = Table.ExpandTableColumn(#"Об’єднані запити1", "Headers", {"№ п/п", "Показник", "Позначення"}, {"N", "Показник", "Позначення"}),
    #"Поділ стовпця за роздільником" = Table.SplitColumn(#"Розгорнуто: Headers", "Показник", Splitter.SplitTextByEachDelimiter({","}, QuoteStyle.Csv, true), {"Показник", "Розмірність"}),
    #"Об’єднані запити2" = Table.NestedJoin(#"Поділ стовпця за роздільником", {"organization code"}, #"Список станцій", {"organization code"}, "Список станцій", JoinKind.LeftOuter),
    #"Розгорнуто: Список станцій" = Table.ExpandTableColumn(#"Об’єднані запити2", "Список станцій", {"organization"}, {"organization"}),
    #"Додане настроюване значення1" = Table.AddColumn(#"Розгорнуто: Список станцій", "last update", each DateTime.LocalNow(), type datetime),
    #"Додане настроюване значення2" = Table.AddColumn(#"Додане настроюване значення1", "Name", each "RAB_W0", type text),
    #"Додане настроюване значення3" = Table.AddColumn(#"Додане настроюване значення2", "Status", each "archived", type text),
    #"Додане настроюване значення5" = Table.AddColumn(#"Додане настроюване значення3", "TableType", each "Загальностанційні показники", type text),
    #"Додане настроюване значення4" = Table.AddColumn(#"Додане настроюване значення5", "Група N4", each null, type number),
    #"Змінений тип3" = Table.TransformColumnTypes(#"Додане настроюване значення4",{{"timestamp", type datetime}, {"N", type text}}),
    #"Видалені інші стовпці" = Table.SelectColumns(#"Змінений тип3",{"Name", "template", "organization code", "organization", "timestamp", "last update", "Status", "N", "Показник", "Розмірність", "Позначення", "Група N1", "Група N2", "Група N3", "Група N4", "Всього", "TableType"})
in
    #"Видалені інші стовпці"