// 900
let
    Source = Excel.Workbook(File.Contents("C:\Users\Vasulevus\Documents\Work\Archives\05356\2018\mak05356_01\05356_000900_01_2018.xls"), null, true),
    #"1" = Source{[Name="05356"]}[Data],
    #"Filtered Rows" = Table.SelectRows(#"1", each ([Column1] <> null and [Column1] <> "      у тому числі:" and [Column1] <> "))" and [Column1] <> "*  - Без  урахування невідшкодованих виплат ліквідаторам аварії на ЧАЕС, малозабезпеченим сім'ям та інвалідам І - ІІ гр." and [Column1] <> "_________________ПАТ ""ДТЕК Західенерго""__________________________________" and [Column1] <> "Види податків та платежів" and [Column1] <> "Довідка" and [Column1] <> "за __січень______ місяці(в)  __2018____ року" and [Column1] <> "місячна, до 25-го  числа кожного місяця , наростаючою сумою з початку року" and [Column1] <> "назва підприємства" and [Column1] <> "про стан розрахунків з бюджетами та позабюджетними фондами" and [Column1] <> "тис.грн (в цілих одиницях)")),
    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.Contains([Column1], "ПАТ") and not Text.Contains([Column1], "року")),
    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows1", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"А", type text}, {"Б", Int64.Type}, {"1", Int64.Type}, {"2", Int64.Type}, {"3", Int64.Type}, {"4", Int64.Type}, {"5", Int64.Type}, {"6", Int64.Type}, {"7", Int64.Type}, {"8", Int64.Type}, {"9", Int64.Type}, {"10", Int64.Type}, {"11", Int64.Type}, {"Column14", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"А", "Види податків та платежів"}, {"Б", "Код рядка"}, {"1", "Заборгованість на початок року перед бюджетом"}, {"2", "у т.ч. недоїмка"}, {"3", "бюджета перед підприємством"}, {"4", "Нараховано (всього)"}, {"5", "Сплачено всього"}, {"6", "У тому числі грошовими коштами"}, {"7", "по постановам КМУ"}, {"8", "Заборгованість на кінець звітного періоду  перед бюджетом"}, {"9", "у т.ч. недоїмка на кінець звітного періоду"}, {"10", "бюджета перед підприємством на кінець звітного періоду"}, {"11", "Довідково з гр.4 нарахов.до сплати розстроч. заборгованості"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","((","",Replacer.ReplaceText,{"Види податків та платежів"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"Види податків та платежів", "Код рядка", "Заборгованість на початок року перед бюджетом", "у т.ч. недоїмка", "бюджета перед підприємством", "Нараховано (всього)", "Сплачено всього", "У тому числі грошовими коштами", "по постановам КМУ", "Заборгованість на кінець звітного періоду  перед бюджетом", "у т.ч. недоїмка на кінець звітного періоду", "бюджета перед підприємством на кінець звітного періоду", "Довідково з гр.4 нарахов.до сплати розстроч. заборгованості"}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"Види податків та платежів", "Код рядка"}, "Attribute", "Value")
in
    #"Unpivoted Other Columns"

//500
let
    Source = Excel.Workbook(File.Contents("C:\Users\Vasulevus\Documents\Work\Archives\05356\2018\mak05356_01\05356_000500_01_2018.xls"), null, true),
    #"1" = Source{[Name="05356"]}[Data],
    #"Filtered Rows" = Table.SelectRows(#"1", each ([Column1] <> null and [Column1] <> "      у тому числі:" and [Column1] <> "))" and [Column1] <> "*  - Без  урахування невідшкодованих виплат ліквідаторам аварії на ЧАЕС, малозабезпеченим сім'ям та інвалідам І - ІІ гр." and [Column1] <> "_________________ПАТ ""ДТЕК Західенерго""__________________________________" and [Column1] <> "Види податків та платежів" and [Column1] <> "Довідка" and [Column1] <> "за __січень______ місяці(в)  __2018____ року" and [Column1] <> "місячна, до 25-го  числа кожного місяця , наростаючою сумою з початку року" and [Column1] <> "назва підприємства" and [Column1] <> "про стан розрахунків з бюджетами та позабюджетними фондами" and [Column1] <> "тис.грн (в цілих одиницях)")),
    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"А", type text}, {"Б", Int64.Type}, {"1", Int64.Type}, {"2", Int64.Type}, {"3", Int64.Type}, {"4", Int64.Type}, {"5", Int64.Type}, {"6", Int64.Type}, {"7", Int64.Type}, {"8", Int64.Type}, {"9", Int64.Type}, {"10", Int64.Type}, {"11", Int64.Type}, {"Column14", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"А", "Види податків та платежів"}, {"Б", "Код рядка"}, {"1", "Заборгованість на початок року перед бюджетом"}, {"2", "у т.ч. недоїмка"}, {"3", "бюджета перед підприємством"}, {"4", "Нараховано (всього)"}, {"5", "Сплачено всього"}, {"6", "У тому числі грошовими коштами"}, {"7", "по постановам КМУ"}, {"8", "Заборгованість на кінець звітного періоду  перед бюджетом"}, {"9", "у т.ч. недоїмка на кінець звітного періоду"}, {"10", "бюджета перед підприємством на кінець звітного періоду"}, {"11", "Довідково з гр.4 нарахов.до сплати розстроч. заборгованості"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","((","",Replacer.ReplaceText,{"Види податків та платежів"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"Види податків та платежів", "Код рядка", "Заборгованість на початок року перед бюджетом", "у т.ч. недоїмка", "бюджета перед підприємством", "Нараховано (всього)", "Сплачено всього", "У тому числі грошовими коштами", "по постановам КМУ", "Заборгованість на кінець звітного періоду  перед бюджетом", "у т.ч. недоїмка на кінець звітного періоду", "бюджета перед підприємством на кінець звітного періоду", "Довідково з гр.4 нарахов.до сплати розстроч. заборгованості"}),
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"Види податків та платежів", "Код рядка"}, "Attribute", "Value")
in
    #"Unpivoted Other Columns"


//ver1.1
let     Source = Excel.Workbook(File.Contents("C:\Users\Vasulevus\Documents\Work\Test\05356_000300_01_2018.xls"), null, true),     #"1" = Source{[Name="05356"]}[Data],     #"Filtered Rows" = Table.SelectRows(#"1", each ([Column1] <> null and [Column1] <> "      у тому числі:" and [Column1] <> "))" and [Column1] <> "*  - Без  урахування невідшкодованих виплат ліквідаторам аварії на ЧАЕС, малозабезпеченим сім'ям та інвалідам І - ІІ гр." and [Column1] <> "_________________ПАТ ""ДТЕК Західенерго""__________________________________" and [Column1] <> "Види податків та платежів" and [Column1] <> "Довідка" and [Column1] <> "за __січень______ місяці(в)  __2018____ року" and [Column1] <> "місячна, до 25-го  числа кожного місяця , наростаючою сумою з початку року" and [Column1] <> "назва підприємства" and [Column1] <> "про стан розрахунків з бюджетами та позабюджетними фондами" and [Column1] <> "тис.грн (в цілих одиницях)")),     #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.Contains([Column1], "ПАТ") and not Text.Contains([Column1], "року")),     #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows1", [PromoteAllScalars=true]),     #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"А", type text}, {"Б", Int64.Type}, {"1", Int64.Type}, {"2", Int64.Type}, {"3", Int64.Type}, {"4", Int64.Type}, {"5", Int64.Type}, {"6", Int64.Type}, {"7", Int64.Type}, {"8", Int64.Type}, {"9", Int64.Type}, {"10", Int64.Type}, {"11", Int64.Type}, {"Column14", Int64.Type}}),     #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"А", "Види податків та платежів"}, {"Б", "Код рядка"}, {"1", "Заборгованість на початок року перед бюджетом"}, {"2", "у т.ч. недоїмка"}, {"3", "бюджета перед підприємством"}, {"4", "Нараховано (всього)"}, {"5", "Сплачено всього"}, {"6", "У тому числі грошовими коштами"}, {"7", "по постановам КМУ"}, {"8", "Заборгованість на кінець звітного періоду  перед бюджетом"}, {"9", "у т.ч. недоїмка на кінець звітного періоду"}, {"10", "бюджета перед підприємством на кінець звітного періоду"}, {"11", "Довідково з гр.4 нарахов.до сплати розстроч. заборгованості"}}),     #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","((","",Replacer.ReplaceText,{"Види податків та платежів"}),     #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"Види податків та платежів", "Код рядка", "Заборгованість на початок року перед бюджетом", "у т.ч. недоїмка", "бюджета перед підприємством", "Нараховано (всього)", "Сплачено всього", "У тому числі грошовими коштами", "по постановам КМУ", "Заборгованість на кінець звітного періоду  перед бюджетом", "у т.ч. недоїмка на кінець звітного періоду", "бюджета перед підприємством на кінець звітного періоду", "Довідково з гр.4 нарахов.до сплати розстроч. заборгованості"}),     #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"Види податків та платежів", "Код рядка"}, "Attribute", "Value"),
    #"Added Custom" = Table.AddColumn(#"Unpivoted Other Columns", "Назва файлу", each "05356_000300_01_2018"),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Added Custom", "Назва файлу", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"Макет", "Код підприємства", "Місяць", "Рік"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Макет", Int64.Type}, {"Код підприємства", Int64.Type}, {"Місяць", Int64.Type}, {"Рік", Int64.Type}})
in
    #"Changed Type1"